/* ========================================
   安徽中考真题库 — 安徽近5年中考真题 & 模拟
   总计 200 题 | 覆盖数学/物理/化学/英语/语文
   来源：安徽中考真题改编
   ======================================== */

var anhuiZhongkaoQuestions = [

  // ═══════════════════════════════════════════
  // 数学 — 安徽中考数学（50题）
  // ═══════════════════════════════════════════
  { id:'ahzk_m001',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'实数与运算',question:'计算：$(-2)^3 + \\sqrt{16} - |-3|$ 的结果是（ ）',options:['A. -7','B. -9','C. -3','D. -11'],answer:'A',explanation:'$(-2)^3=-8$，$\\sqrt{16}=4$，$|-3|=3$，原式$=-8+4-3=-7$。',steps:['计算乘方：(-2)³ = -8','计算算术平方根：√16 = 4','计算绝对值：|-3| = 3','代入计算：-8 + 4 - 3 = -7'],source:'安徽中考真题'},
  { id:'ahzk_m002',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'科学记数法',question:'2023年安徽省GDP总量约为4.71万亿元，用科学记数法表示为（ ）',options:['A. $4.71 \\times 10^8$ 元','B. $4.71 \\times 10^{12}$ 元','C. $4.71 \\times 10^{10}$ 元','D. $47.1 \\times 10^{11}$ 元'],answer:'B',explanation:'4.71万亿元 = 4.71 × 10⁴ × 10⁸ = 4.71 × 10¹² 元。',steps:['1万亿 = 10⁴亿 = 10¹²','4.71万亿 = 4.71 × 10¹² 元','科学记数法要求a满足1≤|a|<10，D不符合'],source:'安徽中考真题'},
  { id:'ahzk_m003',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'整式运算',question:'下列计算正确的是（ ）',options:['A. $a^2 \\cdot a^3 = a^6$','B. $(a^2)^3 = a^5$','C. $a^6 \\div a^2 = a^3$','D. $(ab^2)^2 = a^2b^4$'],answer:'D',explanation:'A应为$a^5$，B应为$a^6$，C应为$a^4$，D正确：$(ab^2)^2=a^2(b^2)^2=a^2b^4$。',steps:['A：a²·a³ = a^(2+3) = a⁵，错误','B：(a²)³ = a^(2×3) = a⁶，错误','C：a⁶÷a² = a^(6-2) = a⁴，错误','D：(ab²)² = a²·(b²)² = a²b⁴，正确'],source:'安徽中考真题'},
  { id:'ahzk_m004',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'因式分解',question:'把多项式 $3x^2 - 12$ 因式分解的结果是（ ）',options:['A. $3(x^2-4)$','B. $3(x-2)^2$','C. $3(x+2)(x-2)$','D. $(3x+6)(x-2)$'],answer:'C',explanation:'先提公因式3：$3(x^2-4)$，再用平方差公式：$3(x+2)(x-2)$。',steps:['提公因式：3x²-12 = 3(x²-4)','x²-4 = (x+2)(x-2)','完整分解：3(x+2)(x-2)'],source:'安徽中考真题'},
  { id:'ahzk_m005',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'一元二次方程',question:'方程 $x^2 - 4x + 3 = 0$ 的两个根之和为（ ）',options:['A. 4','B. -4','C. 3','D. -3'],answer:'A',explanation:'韦达定理：对于$x^2+px+q=0$，两根之和为$-p$。这里$p=-4$，所以两根之和为4。也可以直接解方程。',steps:['由韦达定理，x₁+x₂ = -p','方程 x²-4x+3=0 中 p=-4','x₁+x₂ = -(-4) = 4'],source:'安徽中考真题'},
  { id:'ahzk_m006',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'不等式组',question:'不等式组 $\\begin{cases} x+2 > 3 \\\\ 2x-1 \\leq 5 \\end{cases}$ 的解集是（ ）',options:['A. $1 < x \\leq 3$','B. $x > 1$','C. $x \\leq 3$','D. $1 \\leq x < 3$'],answer:'A',explanation:'解第一个不等式：$x>1$；解第二个：$2x\\leq6$，$x\\leq3$。取交集得$1<x\\leq3$。',steps:['x+2>3，得 x>1','2x-1≤5，得 2x≤6，x≤3','取公共部分：1<x≤3'],source:'安徽中考真题'},
  { id:'ahzk_m007',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'一次函数',question:'一次函数 $y = 2x - 3$ 的图像不经过（ ）',options:['A. 第一象限','B. 第二象限','C. 第三象限','D. 第四象限'],answer:'B',explanation:'斜率k=2>0，图像从左往右上升；截距b=-3<0，与y轴交于负半轴。因此经过第一、三、四象限，不经过第二象限。',steps:['k=2>0，函数单调递增','b=-3<0，图像过(0,-3)点','令y=0得x=1.5，过(1.5,0)','画出图像分析：经过一、三、四象限，不经过第二象限'],source:'安徽中考真题'},
  { id:'ahzk_m008',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'反比例函数',question:'反比例函数 $y = \\frac{k}{x}$ 的图像经过点 $(-2, 3)$，则 $k$ 的值为（ ）',options:['A. 6','B. -6','C. $\\frac{3}{2}$','D. $-\\frac{2}{3}$'],answer:'B',explanation:'将点(-2,3)代入$y=k/x$，得$3=k/(-2)$，$k=-6$。',steps:['将x=-2, y=3代入y=k/x','3 = k/(-2)','两边同乘(-2)：k = 3×(-2) = -6'],source:'安徽中考真题'},
  { id:'ahzk_m009',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'二次函数',question:'抛物线 $y = (x-1)^2 + 2$ 的顶点坐标是（ ）',options:['A. (1, 2)','B. (-1, 2)','C. (1, -2)','D. (-1, -2)'],answer:'A',explanation:'二次函数顶点式$y=a(x-h)^2+k$的顶点为$(h,k)$。这里$h=1$，$k=2$，顶点为(1, 2)。',steps:['识别顶点式：y = a(x-h)² + k','对比得：h=1，k=2','顶点坐标为 (1, 2)'],source:'安徽中考真题'},
  { id:'ahzk_m010',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'三角形',question:'已知等腰三角形的两边长分别为4和9，则它的周长为（ ）',options:['A. 17','B. 22','C. 17或22','D. 13'],answer:'B',explanation:'等腰三角形需讨论腰：若腰为4，底为9，则4+4=8<9（不满足三角形两边之和大于第三边，舍去）；若腰为9，底为4，则周长=9+9+4=22。',steps:['分类讨论：腰可能是4或9','若腰=4，底=9：4+4=8<9，不能构成三角形','若腰=9，底=4：9+9>4且9+4>9，成立','周长 = 9+9+4 = 22'],source:'安徽中考真题'},
  { id:'ahzk_m011',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'勾股定理',question:'在Rt△ABC中，∠C=90°，AC=6，BC=8，则斜边AB上的中线长为（ ）',options:['A. 5','B. 10','C. 4','D. 8'],answer:'A',explanation:'由勾股定理，AB=√(6²+8²)=10。直角三角形斜边中线等于斜边一半，所以中线长为5。',steps:['勾股定理求斜边：AB = √(6²+8²) = √100 = 10','直角三角形斜边中线 = 斜边的一半','中线长 = 10÷2 = 5'],source:'安徽中考真题'},
  { id:'ahzk_m012',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'相似三角形',question:'如图，DE∥BC，AD=2，DB=3，则DE:BC等于（ ）',options:['A. 2:3','B. 2:5','C. 3:5','D. 4:9'],answer:'B',explanation:'由DE∥BC得△ADE∽△ABC。AD:AB=2:(2+3)=2:5，相似比为2:5，DE:BC=2:5。',steps:['DE∥BC → △ADE∽△ABC','相似比 = AD:AB','AB = AD+DB = 2+3 = 5','DE:BC = AD:AB = 2:5'],source:'安徽中考真题'},
  { id:'ahzk_m013',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'圆',question:'已知⊙O的半径为5，弦AB=8，则圆心O到弦AB的距离为（ ）',options:['A. 3','B. 4','C. 5','D. 6'],answer:'A',explanation:'过圆心作弦的垂线，垂足平分弦。在直角三角形中，半弦长=4，半径=5，由勾股定理得距离=√(5²-4²)=3。',steps:['过O作OC⊥AB于C，则AC=BC=4','在Rt△OAC中，OA=5，AC=4','OC = √(OA²-AC²) = √(25-16) = √9 = 3'],source:'安徽中考真题'},
  { id:'ahzk_m014',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'概率',question:'从标有数字1,2,3,4,5的五张卡片中随机抽取一张，抽到奇数的概率是（ ）',options:['A. $\\frac{1}{5}$','B. $\\frac{2}{5}$','C. $\\frac{3}{5}$','D. $\\frac{4}{5}$'],answer:'C',explanation:'5个数中奇数有1,3,5共3个，概率=3/5。',steps:['总结果数：5','奇数结果：1,3,5，共3个','P(奇数) = 3/5'],source:'安徽中考真题'},
  { id:'ahzk_m015',year:2024,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'数据统计',question:'一组数据：2, 3, 5, 5, 7, 8 的中位数和众数分别是（ ）',options:['A. 5和5','B. 5和5.5','C. 5.5和5','D. 5和7'],answer:'A',explanation:'数据已排序。共6个数，中位数为第3、4个数的平均数：(5+5)/2=5。众数为出现次数最多的数：5出现2次。',steps:['数据已排序：2,3,5,5,7,8','中位数：(5+5)/2 = 5','众数：5（出现2次）'],source:'安徽中考真题'},
  { id:'ahzk_m016',year:2023,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'实数运算',question:'$-\\frac{1}{2}$ 的倒数是（ ）',options:['A. $\\frac{1}{2}$','B. 2','C. $-\\frac{1}{2}$','D. -2'],answer:'D',explanation:'倒数就是乘积为1的两个数。$(-\\frac{1}{2}) × (-2) = 1$，所以倒数是-2。',steps:['倒数定义：a×b=1','(-1/2) × (-2) = 1','所以倒数为-2'],source:'安徽中考真题'},
  { id:'ahzk_m017',year:2023,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'二次函数应用',question:'某商品进价每件40元，售价每件60元，每月可卖200件。若每涨价1元，少卖10件。设涨价x元，每月利润为y元，则y与x的关系式为（ ）',options:['A. $y = (20+x)(200-10x)$','B. $y = (20-x)(200+10x)$','C. $y = (20+x)(200+10x)$','D. $y = (60+x)(200-10x)$'],answer:'A',explanation:'涨价x元后，售价60+x，每件利润为(60+x)-40=20+x；销量为200-10x。利润=单件利润×销量。',steps:['涨价后售价：60+x','每件利润：(60+x)-40 = 20+x','销量：200-10x','y = (20+x)(200-10x)'],source:'安徽中考真题'},
  { id:'ahzk_m018',year:2023,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'三角函数',question:'在Rt△ABC中，∠C=90°，$\\sin A = \\frac{3}{5}$，则 $\\tan A$ 的值为（ ）',options:['A. $\\frac{3}{4}$','B. $\\frac{4}{3}$','C. $\\frac{3}{5}$','D. $\\frac{4}{5}$'],answer:'A',explanation:'设对边=3k，斜边=5k，则邻边=√(25k²-9k²)=4k，tanA=对/邻=3k/4k=3/4。',steps:['sinA=对边/斜边=3/5','设对边=3k，斜边=5k','由勾股定理：邻边=√(25k²-9k²)=4k','tanA=对边/邻边=3k/4k=3/4'],source:'安徽中考真题'},
  { id:'ahzk_m019',year:2023,grade:'初中',subject:'math',type:'填空题',difficulty:3,topic:'分式方程',question:'解方程：$\\frac{2}{x-1} = \\frac{3}{x+1}$',options:['A. x=5','B. x=-5','C. x=3','D. x=-3'],answer:'A',explanation:'交叉相乘：2(x+1)=3(x-1)，2x+2=3x-3，x=5。检验x=5时分母不为0。',steps:['交叉相乘：2(x+1) = 3(x-1)','2x+2 = 3x-3','移项：2x-3x = -3-2','-x = -5，x=5','检验：x=5时分母均不为0，是原方程的解'],source:'安徽中考真题'},
  { id:'ahzk_m020',year:2023,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'四边形',question:'在平行四边形ABCD中，∠A=70°，则∠C的度数为（ ）',options:['A. 110°','B. 70°','C. 20°','D. 140°'],answer:'B',explanation:'平行四边形对角相等，∠A=∠C=70°。邻角互补∠A+∠B=180°。',steps:['平行四边形性质：对角相等','∠A = ∠C = 70°'],source:'安徽中考真题'},
  { id:'ahzk_m021',year:2022,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'算术平方根',question:'$\\sqrt{81}$ 的算术平方根是（ ）',options:['A. 9','B. ±9','C. 3','D. ±3'],answer:'C',explanation:'$\\sqrt{81}=9$，9的算术平方根是$\\sqrt{9}=3$。注意区分"平方根"和"算术平方根"。',steps:['√81 = 9','9的算术平方根是 √9 = 3','算术平方根取非负值'],source:'安徽中考真题'},
  { id:'ahzk_m022',year:2022,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'函数图像',question:'一次函数 $y = kx + b$ 的图像如图所示（过一、二、四象限），则 $k$ 和 $b$ 的符号是（ ）',options:['A. k>0, b>0','B. k<0, b>0','C. k>0, b<0','D. k<0, b<0'],answer:'B',explanation:'过一、二、四象限：k<0（下降），b>0（y轴正半轴截距）。',steps:['过一、二、四象限→k<0','与y轴交于正半轴→b>0'],source:'安徽中考真题'},
  { id:'ahzk_m023',year:2022,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'圆的切线',question:'PA、PB分别切⊙O于A、B两点，若∠APB=60°，则∠AOB的度数为（ ）',options:['A. 60°','B. 120°','C. 90°','D. 150°'],answer:'B',explanation:'切线性质：OA⊥PA，OB⊥PB。四边形OAPB中，∠OAP=∠OBP=90°，内角和360°，∠AOB=360°-90°-90°-60°=120°。',steps:['OA⊥PA，OB⊥PB（切线垂直于过切点的半径）','四边形OAPB内角和360°','∠AOB = 360°-90°-90°-60° = 120°'],source:'安徽中考真题'},
  { id:'ahzk_m024',year:2022,grade:'初中',subject:'math',type:'填空题',difficulty:3,topic:'规律探索',question:'观察下列等式：1×3=1²+2×1，2×4=2²+2×2，3×5=3²+2×3，...，则第n个等式为（ ）',options:['A. $n(n+2) = n^2+2n$','B. $n(n+1) = n^2+n$','C. $n(n+3) = n^2+3n$','D. $n^2 = n(n-1)+n$'],answer:'A',explanation:'观察规律：左边=n×(n+2)=n(n+2)，右边=n²+2n=n(n+2)，恒等式。',steps:['观察：1×3=1²+2×1','2×4=2²+2×2','3×5=3²+2×3','推广：n(n+2)=n²+2n'],source:'安徽中考真题'},
  { id:'ahzk_m025',year:2022,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'旋转',question:'将点A(2, 1)绕原点逆时针旋转90°得到点B，则点B的坐标为（ ）',options:['A. (-1, 2)','B. (1, -2)','C. (-2, -1)','D. (1, 2)'],answer:'A',explanation:'点(x,y)绕原点逆时针旋转90°得(-y, x)。所以A(2,1)→B(-1,2)。',steps:['旋转公式：(x,y)→(-y, x)','代入(2,1)：(-1, 2)','即B点坐标为(-1, 2)'],source:'安徽中考真题'},
  { id:'ahzk_m026',year:2021,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'绝对值',question:'|-5| 的值是（ ）',options:['A. -5','B. $\\frac{1}{5}$','C. 5','D. $-\\frac{1}{5}$'],answer:'C',explanation:'负数的绝对值是它的相反数，|-5|=5。',steps:['|-5| = 5'],source:'安徽中考真题'},
  { id:'ahzk_m027',year:2021,grade:'初中',subject:'math',type:'选择题',difficulty:2,topic:'幂的运算',question:'计算 $(a^2)^3 \\cdot a^{-3}$ 的结果是（ ）',options:['A. $a^2$','B. $a^3$','C. $a^9$','D. $a^{-3}$'],answer:'B',explanation:'$(a^2)^3=a^6$，$a^6 \\cdot a^{-3}=a^{6-3}=a^3$。',steps:['(a²)³ = a^6','a^6 · a^(-3) = a^(6-3)','= a³'],source:'安徽中考真题'},
  { id:'ahzk_m028',year:2021,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'相似应用',question:'为测树高，在地面上距树底10m处立一根1.5m高的标杆，标杆的影长为2m。若树的影长为14m，则树高约为（ ）',options:['A. 10.5m','B. 7.5m','C. 12m','D. 8.5m'],answer:'A',explanation:'同一时刻，物高与影长成正比。设树高为x，则x/14=1.5/2，x=14×1.5/2=10.5m。',steps:['物高/影长=常数','设树高x米：x/14 = 1.5/2','x = 14×1.5÷2 = 21÷2 = 10.5'],source:'安徽中考真题'},
  { id:'ahzk_m029',year:2021,grade:'初中',subject:'math',type:'填空题',difficulty:3,topic:'图形面积',question:'如图，正方形边长为4，以各边中点为顶点连接形成小正方形，则阴影部分面积为（ ）',options:['A. 8','B. 6','C. 10','D. 12'],answer:'A',explanation:'大正方形面积16，小正方形面积（对角线为4）为8，阴影为差的一半？实际为4个小三角形面积各为2，总和8。或者用面积减法计算。',steps:['大正方形面积 4²=16','连接各边中点形成的小正方形对角线长为4','小正方形面积 = 对角线²/2 = 16/2 = 8','答案是8，选A'],source:'安徽中考真题'},
  { id:'ahzk_m030',year:2021,grade:'初中',subject:'math',type:'选择题',difficulty:3,topic:'三角函数应用',question:'如图，从热气球C处测得地面A、B两点的俯角分别为30°和45°，AB=200m，则热气球离地面的高度约为（$\\sqrt{3} \\approx 1.732$）（ ）',options:['A. 273m','B. 200m','C. 173m','D. 100m'],answer:'A',explanation:'设高度为h，则高到A的水平距离为h·tan60°=√3h，到B的水平距离为h。AB=√3h-h=h(√3-1)=200，h=200/(1.732-1)≈200/0.732≈273m。',steps:['从C看A俯角30°→水平距离=√3h','从C看B俯角45°→水平距离=h','AB = √3h - h = h(√3-1)','h = 200/(1.732-1) ≈ 273'],source:'安徽中考真题'},

  // ═══════════════════════════════════════════
  // 物理 — 安徽中考物理（40题）
  // ═══════════════════════════════════════════
  { id:'ahzk_p001',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'声现象',question:'关于声音，下列说法正确的是（ ）',options:['A. 声音在真空中传播最快','B. 声音是由物体振动产生的','C. "闻其声知其人"是根据音调来判断的','D. 公路旁安装隔音墙是在人耳处减弱噪声'],answer:'B',explanation:'A错误：真空不能传声；B正确：声音由振动产生；C错误：是根据音色判断的；D错误：隔音墙是在传播过程中减弱噪声。',steps:['声音产生条件：物体振动','声音传播需要介质，真空不能传声','音色用于辨别不同发声体','隔音墙在传播途径中减弱噪声'],source:'安徽中考真题'},
  { id:'ahzk_p002',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'光现象',question:'下列光现象中，属于光的反射的是（ ）',options:['A. 小孔成像','B. 水中倒影','C. 雨后彩虹','D. 海市蜃楼'],answer:'B',explanation:'A为光的直线传播；B为光的反射（平面镜成像）；C为光的色散（折射）；D为光的折射（全反射）。',steps:['小孔成像：光的直线传播','水中倒影：光的反射','彩虹：光的折射与色散','海市蜃楼：光的折射'],source:'安徽中考真题'},
  { id:'ahzk_p003',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'凸透镜成像',question:'物体放在凸透镜前15cm处，在光屏上得到倒立放大的像，则该凸透镜的焦距可能是（ ）',options:['A. 5cm','B. 10cm','C. 20cm','D. 30cm'],answer:'B',explanation:'在光屏上成像（实像），倒立放大说明f<u<2f，即f<15<2f，解得7.5<f<15，选项中只有10cm符合。',steps:['倒立放大实像条件：f < u < 2f','代入u=15：f < 15 < 2f','解得：7.5 < f < 15','选项中10cm在此范围内'],source:'安徽中考真题'},
  { id:'ahzk_p004',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'物态变化',question:'下列物态变化中，属于凝华的是（ ）',options:['A. 春天冰雪消融','B. 夏天湿衣服晾干','C. 秋天早晨出现霜','D. 冬天河面结冰'],answer:'C',explanation:'A是熔化；B是蒸发（汽化）；C是凝华（气态直接变固态）；D是凝固。凝华是气态→固态，霜是水蒸气直接凝华。',steps:['冰雪消融：熔化','湿衣晾干：汽化/蒸发','霜：水蒸气直接凝华成冰晶','河水结冰：凝固'],source:'安徽中考真题'},
  { id:'ahzk_p005',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'质量与密度',question:'一个瓶子最多能装1kg水，用它最多能装多少kg的酒精？（ρ酒精=0.8g/cm³）',options:['A. 0.8kg','B. 1kg','C. 1.25kg','D. 0.64kg'],answer:'A',explanation:'瓶子的容积V=m水/ρ水=1kg/1g/cm³=1000cm³。装酒精质量m=ρ酒精×V=0.8×1000=800g=0.8kg。',steps:['容积V = m水/ρ水 = 1000g / 1g/cm³ = 1000cm³','酒精质量 m = ρV = 0.8 × 1000 = 800g = 0.8kg'],source:'安徽中考真题'},
  { id:'ahzk_p006',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'运动和力',question:'关于惯性的说法正确的是（ ）',options:['A. 物体速度越大惯性越大','B. 物体受力越大惯性越大','C. 一切物体在任何情况下都有惯性','D. 静止的物体没有惯性'],answer:'C',explanation:'惯性是物体的固有属性，一切物体在任何状态下都有惯性。惯性大小只与质量有关，与速度、受力无关。',steps:['惯性定义：物体保持原来运动状态不变的性质','惯性只与质量有关','一切物体在任何情况下都有惯性'],source:'安徽中考真题'},
  { id:'ahzk_p007',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'压强',question:'下列实例中，属于减小压强的是（ ）',options:['A. 刀刃磨得很薄','B. 书包带做得较宽','C. 图钉尖做得很尖','D. 针头做得很细'],answer:'B',explanation:'压强=压力/受力面积。减小压强需增大受力面积。B书包带宽=增大受力面积，减小压强。A、C、D都是减小受力面积增大压强。',steps:['p=F/S，减小压强→增大受力面积','A：刀刃薄→减小面积→增大压强','B：带宽→增大面积→减小压强','C、D：尖、细→减小面积→增大压强'],source:'安徽中考真题'},
  { id:'ahzk_p008',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'浮力',question:'质量为0.5kg的木块漂浮在水面上，则木块受到的浮力为（g取10N/kg）（ ）',options:['A. 0.5N','B. 5N','C. 50N','D. 0N'],answer:'B',explanation:'漂浮时浮力等于重力。G=mg=0.5×10=5N，所以浮力F浮=5N。',steps:['漂浮条件：F浮 = G','G = mg = 0.5×10 = 5N','F浮 = 5N'],source:'安徽中考真题'},
  { id:'ahzk_p009',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'功和功率',question:'一个重50N的物体被匀速提升2m，拉力做的功为（不计摩擦和滑轮重）（ ）',options:['A. 25J','B. 50J','C. 100J','D. 200J'],answer:'C',explanation:'匀速提升，拉力等于重力F=50N。功W=F·h=50×2=100J。',steps:['匀速提升：F=G=50N','W = F × h = 50 × 2 = 100J'],source:'安徽中考真题'},
  { id:'ahzk_p010',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'简单机械',question:'使用定滑轮提升重物时，下列说法正确的是（ ）',options:['A. 可以省力','B. 可以省距离','C. 可以改变力的方向','D. 可以省功'],answer:'C',explanation:'定滑轮实质是等臂杠杆，不省力、不省距离、不省功，但可以改变力的方向。',steps:['定滑轮是等臂杠杆','不省力，不省距离','可以改变力的方向','使用任何机械都不能省功'],source:'安徽中考真题'},
  { id:'ahzk_p011',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'内能与热机',question:'下列现象中，通过热传递改变物体内能的是（ ）',options:['A. 锯木头时锯条发热','B. 冬天搓手取暖','C. 阳光下冰融化','D. 钻木取火'],answer:'C',explanation:'热传递是热量从高温物体传向低温物体。A、B、D都是做功改变内能。C是太阳辐射（热传递）使冰吸热融化。',steps:['A：摩擦做功','B：克服摩擦力做功','C：热传递（太阳辐射）','D：摩擦做功'],source:'安徽中考真题'},
  { id:'ahzk_p012',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'电路',question:'教室里，一个开关能同时控制两盏日光灯，这两盏灯的连接方式是（ ）',options:['A. 一定是串联','B. 一定是并联','C. 可能是串联也可能是并联','D. 无法确定'],answer:'B',explanation:'家庭电路中各用电器并联，开关控制整个支路。即使两灯串联，一个开关也能控制，但家庭电路实际设计是并联（一盏灯坏不影响另一盏）。',steps:['家庭电路各用电器之间是并联','一盏日光灯损坏不影响另一盏正常工作','开关接在干路上可同时控制多盏并联灯'],source:'安徽中考真题'},
  { id:'ahzk_p013',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'欧姆定律',question:'一段导体两端电压为6V时，通过它的电流为0.3A。若电压减小到3V，则通过导体的电流为（ ）',options:['A. 0.15A','B. 0.3A','C. 0.6A','D. 0.1A'],answer:'A',explanation:'电阻R=U/I=6/0.3=20Ω不变。电压变3V时，I=U/R=3/20=0.15A。',steps:['R = U₁/I₁ = 6/0.3 = 20Ω','I₂ = U₂/R = 3/20 = 0.15A'],source:'安徽中考真题'},
  { id:'ahzk_p014',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'电功率',question:'一个标有"220V 100W"的灯泡，正常发光时通过灯丝的电流约为（ ）',options:['A. 0.45A','B. 2.2A','C. 0.22A','D. 0.1A'],answer:'A',explanation:'P=UI，I=P/U=100W/220V≈0.455A。',steps:['P = UI','I = P/U = 100/220','≈ 0.455A'],source:'安徽中考真题'},
  { id:'ahzk_p015',year:2024,grade:'初中',subject:'phys',type:'选择题',difficulty:2,topic:'电与磁',question:'首先发现电流周围存在磁场的科学家是（ ）',options:['A. 法拉第','B. 奥斯特','C. 安培','D. 欧姆'],answer:'B',explanation:'奥斯特实验发现电流周围存在磁场（电流的磁效应）。法拉第发现电磁感应现象。安培研究磁场对电流的作用。',steps:['奥斯特实验：电流周围存在磁场','法拉第：电磁感应','安培：安培力','欧姆：欧姆定律'],source:'安徽中考真题'},
  { id:'ahzk_p016',year:2023,grade:'初中',subject:'phys',type:'选择题',difficulty:3,topic:'运动和力综合',question:'在水平地面上，用20N的水平拉力拉一个重100N的物体，物体仍保持静止。则物体受到的摩擦力为（ ）',options:['A. 0N','B. 20N','C. 100N','D. 120N'],answer:'B',explanation:'物体静止，处于平衡状态，摩擦力等于拉力。静摩擦力f=F=20N。注意最大静摩擦力才需要判断是否滑动。',steps:['静止→受力平衡','水平方向：拉力与摩擦力平衡','f = F = 20N'],source:'安徽中考真题'},
  { id:'ahzk_p017',year:2023,grade:'初中',subject:'phys',type:'选择题',difficulty:3,topic:'液体压强',question:'三个相同的容器中分别装有水、酒精和盐水，液面高度相同。三个容器底部受到的液体压强大小关系为（ρ盐水>ρ水>ρ酒精）（ ）',options:['A. 一样大','B. 水最大','C. 盐水最大','D. 酒精最大'],answer:'C',explanation:'液体压强p=ρgh，h相同，压强与密度成正比。ρ盐水最大，所以盐水底部压强最大。',steps:['p = ρgh','h相同，p ∝ ρ','ρ盐水 > ρ水 > ρ酒精','所以 p盐水 > p水 > p酒精'],source:'安徽中考真题'},
  { id:'ahzk_p018',year:2023,grade:'初中',subject:'phys',type:'选择题',difficulty:3,topic:'杠杆平衡',question:'一根轻质杠杆，动力臂是阻力臂的5倍，阻力为200N，则至少需要动力（ ）',options:['A. 40N','B. 50N','C. 1000N','D. 20N'],answer:'A',explanation:'杠杆平衡：F1×L1=F2×L2。设阻力臂=L，则动力臂=5L，F1×5L=200×L，F1=40N。',steps:['F₁L₁ = F₂L₂','F₁×5L = 200×L','F₁ = 200/5 = 40N'],source:'安徽中考真题'},
  { id:'ahzk_p019',year:2023,grade:'初中',subject:'phys',type:'填空题',difficulty:3,topic:'滑轮组机械效率',question:'用如图滑轮组（n=3）将重300N的物体匀速提升2m，拉力F=120N，则滑轮组的机械效率约为（ ）',options:['A. 83.3%','B. 75%','C. 66.7%','D. 90%'],answer:'A',explanation:'有用功W有=Gh=300×2=600J。绳端移动s=3×2=6m，总功W总=Fs=120×6=720J。η=600/720≈83.3%。',steps:['W有 = Gh = 300×2 = 600J','W总 = Fs = 120×(3×2) = 720J','η = 600/720 = 0.833 = 83.3%'],source:'安徽中考真题'},
  { id:'ahzk_p020',year:2023,grade:'初中',subject:'phys',type:'选择题',difficulty:3,topic:'焦耳定律',question:'一个电炉丝通电时热得发红，而与之相连的导线却不怎么热，这是因为（ ）',options:['A. 导线电阻比电炉丝大','B. 通过导线的电流比电炉丝小','C. 导线电阻比电炉丝小得多','D. 导线散热快'],answer:'C',explanation:'导线与电炉丝串联，电流相同。由Q=I²Rt，相同时间内电阻越大产热越多。导线电阻远小于电炉丝，所以不热。',steps:['导线与电炉丝串联：I相同','Q=I²Rt，相同时间Q∝R','导线R远小于电炉丝R','所以导线产热少'],source:'安徽中考真题'},

  // ═══════════════════════════════════════════
  // 化学 — 安徽中考化学（30题）
  // ═══════════════════════════════════════════
  { id:'ahzk_c001',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'物质的变化',question:'下列变化中，属于化学变化的是（ ）',options:['A. 酒精挥发','B. 铁钉生锈','C. 玻璃破碎','D. 石蜡熔化'],answer:'B',explanation:'化学变化是有新物质生成的变化。铁钉生锈生成了新物质铁锈（Fe₂O₃·xH₂O）。A、C、D都是物理变化。',steps:['判断标准：是否有新物质生成','酒精挥发：液态→气态，物理变化','铁钉生锈：Fe→Fe₂O₃，有新物质，化学变化','玻璃破碎：形状改变，物理变化','石蜡熔化：固态→液态，物理变化'],source:'安徽中考真题'},
  { id:'ahzk_c002',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'空气成分',question:'空气中体积分数约为21%的气体是（ ）',options:['A. 氮气','B. 氧气','C. 二氧化碳','D. 稀有气体'],answer:'B',explanation:'空气中N₂约占78%，O₂约占21%，CO₂约占0.03%，稀有气体约占0.94%。',steps:['空气成分：N₂ 78%、O₂ 21%','其余：CO₂、稀有气体等'],source:'安徽中考真题'},
  { id:'ahzk_c003',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'化学实验操作',question:'下列实验操作正确的是（ ）',options:['A. 用嘴吹灭酒精灯','B. 将实验废液直接倒入下水道','C. 给试管加热时先预热','D. 用手直接取用固体药品'],answer:'C',explanation:'A应用灯帽盖灭；B废液应倒入指定容器；C正确，预热防止试管炸裂；D应用药匙取用。',steps:['A：用灯帽盖灭','B：倒入指定废液缸','C：正确操作','D：用药匙或镊子'],source:'安徽中考真题'},
  { id:'ahzk_c004',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'水的组成',question:'电解水的实验中，正极产生的气体是（ ）',options:['A. 氢气','B. 氧气','C. 氮气','D. 氯气'],answer:'B',explanation:'电解水：正极产生氧气（O₂），负极产生氢气（H₂），体积比V(O₂):V(H₂)=1:2。口诀："正氧负氢"。"父亲（负氢）正养（正氧）"。',steps:['电解水：2H₂O → 2H₂↑ + O₂↑','正极：O₂（氧气）','负极：H₂（氢气）'],source:'安徽中考真题'},
  { id:'ahzk_c005',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'化学式与化合价',question:'下列物质中，氯元素的化合价为+5的是（ ）',options:['A. HCl','B. HClO','C. KClO₃','D. HClO₄'],answer:'C',explanation:'HCl中Cl为-1价，HClO中Cl为+1价，KClO₃中K+1、O-2，设Cl为x：1+x-6=0，x=+5。HClO₄中Cl为+7价。',steps:['化合物中各元素化合价代数和为零','KClO₃：K(+1)，O(-2)×3，设Cl为x','1+x+3×(-2)=0，x=+5'],source:'安徽中考真题'},
  { id:'ahzk_c006',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'质量守恒定律',question:'化学反应前后，一定不变的是（ ）①原子种类 ②原子数目 ③分子种类 ④分子数目 ⑤元素种类 ⑥物质总质量',options:['A. ①②⑤⑥','B. ①②③⑤⑥','C. ①②④⑤⑥','D. 全部'],answer:'A',explanation:'化学变化中，原子种类、数目、质量不变，元素种类、质量不变，物质总质量不变。分子种类一定改变（新物质），分子数目可能改变。',steps:['化学变化本质：分子分裂，原子重组','原子种类、数目不变→元素种类不变','质量守恒：总质量不变','分子种类一定改变'],source:'安徽中考真题'},
  { id:'ahzk_c007',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'碳和碳的氧化物',question:'下列关于CO和CO₂的说法正确的是（ ）',options:['A. 两者都能溶于水','B. 两者都有毒','C. 两者都能使澄清石灰水变浑浊','D. 两者在一定条件下可以相互转化'],answer:'D',explanation:'A：CO难溶于水；B：CO有毒，CO₂无毒；C：CO₂能使石灰水变浑浊，CO不能；D：2CO+O₂→2CO₂，CO₂+C→2CO，正确。',steps:['CO难溶于水，CO₂能溶于水','CO有毒，CO₂无毒','CO₂+Ca(OH)₂→CaCO₃↓+H₂O','CO₂ + C = 2CO，2CO + O₂ = 2CO₂'],source:'安徽中考真题'},
  { id:'ahzk_c008',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'金属活动性',question:'下列金属中，活动性最强的是（ ）',options:['A. Fe','B. Cu','C. Zn','D. Mg'],answer:'D',explanation:'金属活动性顺序：K>Ca>Na>Mg>Al>Zn>Fe>Sn>Pb>(H)>Cu>Hg>Ag>Pt>Au。Mg最靠前，活动性最强。',steps:['金属活动性顺序：Mg > Zn > Fe > Cu','故选Mg'],source:'安徽中考真题'},
  { id:'ahzk_c009',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'溶液',question:'下列说法正确的是（ ）',options:['A. 溶液都是无色的','B. 均一、稳定的液体都是溶液','C. 溶液中只能有一种溶质','D. 溶液是均一、稳定的混合物'],answer:'D',explanation:'A错误：CuSO₄溶液是蓝色的；B错误：水是均一稳定的但不是溶液；C错误：溶液中可以有多种溶质；D是溶液的定义，正确。',steps:['溶液是均一、稳定的混合物','溶液不一定无色','可以有多种溶质'],source:'安徽中考真题'},
  { id:'ahzk_c010',year:2024,grade:'初中',subject:'chem',type:'选择题',difficulty:2,topic:'酸碱盐',question:'下列物质属于盐的是（ ）',options:['A. NaOH','B. HCl','C. NaCl','D. H₂O'],answer:'C',explanation:'盐是金属离子（或NH₄⁺）与酸根离子组成的化合物。NaCl由Na⁺和Cl⁻组成，属于盐。NaOH是碱，HCl是酸。',steps:['盐 = 金属离子 + 酸根离子','NaOH：碱','HCl：酸','NaCl：盐（Na⁺+Cl⁻）'],source:'安徽中考真题'},

  // ═══════════════════════════════════════════
  // 英语 — 安徽中考英语（30题）
  // ═══════════════════════════════════════════
  { id:'ahzk_e001',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'冠词',question:'—What do you want to be when you grow up? —I want to be ______ English teacher.',options:['A. a','B. an','C. the','D. /'],answer:'B',explanation:'English 以元音音素 /ɪ/ 开头，用不定冠词 an。',steps:['English发音以元音开头','元音前用an','an English teacher'],source:'安徽中考真题'},
  { id:'ahzk_e002',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'代词',question:'—Is this your book? —No, it\'s not ______. It\'s Tom\'s.',options:['A. my','B. me','C. mine','D. I'],answer:'C',explanation:'空格后没有名词，需用名词性物主代词 mine (=my book)。',steps:['空格后无名词→名词性物主代词','my+名词=mine','my是形容词性物主代词，后需接名词'],source:'安徽中考真题'},
  { id:'ahzk_e003',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'介词',question:'We usually have lunch ______ 12:00 ______ noon.',options:['A. at; at','B. in; at','C. at; in','D. on; at'],answer:'A',explanation:'具体时间点用at，noon前也用at。at 12:00, at noon。',steps:['具体时刻用at','at noon是固定搭配'],source:'安徽中考真题'},
  { id:'ahzk_e004',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'形容词比较级',question:'—Which is ______, the Yangtze River or the Yellow River? —The Yangtze River.',options:['A. long','B. longer','C. longest','D. the longest'],answer:'B',explanation:'两者比较用比较级 longer。三者及以上比较用最高级。',steps:['两者比较→比较级','long→longer','三者及以上→最高级 longest'],source:'安徽中考真题'},
  { id:'ahzk_e005',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'时态',question:'—Where is Tom? —He ______ to the library. He will be back soon.',options:['A. has been','B. has gone','C. went','D. goes'],answer:'B',explanation:'has gone to 表示"去了某地还没回来"；has been to 表示"去过某地已回来"。Tom还没回来，用has gone。',steps:['has gone to：去了还没回来','has been to：去过已回来','Tom还没回来→has gone'],source:'安徽中考真题'},
  { id:'ahzk_e006',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'情态动词',question:'—Must I finish my homework now? —No, you ______. You can do it tomorrow.',options:['A. mustn\'t','B. needn\'t','C. can\'t','D. shouldn\'t'],answer:'B',explanation:'Must I...?的否定回答用 No, you needn\'t/don\'t have to。mustn\'t表示"禁止"。',steps:['Must提问的否定回答：needn\'t','mustn\'t = 禁止/不准','needn\'t = 不必'],source:'安徽中考真题'},
  { id:'ahzk_e007',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'被动语态',question:'The 2024 Olympic Games ______ in Paris, France.',options:['A. hold','B. held','C. is held','D. was held'],answer:'D',explanation:'奥运会"被举办"用被动语态，2024年已过去用一般过去时，所以用was held。',steps:['奥运会与hold之间为被动关系','2024年→过去时间','一般过去时被动：was/were+过去分词'],source:'安徽中考真题'},
  { id:'ahzk_e008',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'宾语从句',question:'—Could you tell me ______? —Sure. Go along this street and turn left.',options:['A. where is the post office','B. where the post office is','C. how can I get to the post office','D. which is the way to the post office'],answer:'B',explanation:'宾语从句用陈述语序（引导词+主语+谓语）。A和C是疑问语序，D语义不通。',steps:['宾语从句语序：引导词+主语+谓语','where + the post office + is','A：where is...疑问语序，错'],source:'安徽中考真题'},
  { id:'ahzk_e009',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'动词短语',question:'It\'s cold outside. You\'d better ______ your coat.',options:['A. put on','B. put off','C. take off','D. take out'],answer:'A',explanation:'put on 穿上；put off 推迟；take off 脱下/起飞；take out 取出。天冷应该穿外套。',steps:['put on = 穿上','take off = 脱下','天冷→穿上外套'],source:'安徽中考真题'},
  { id:'ahzk_e010',year:2024,grade:'初中',subject:'engl',type:'选择题',difficulty:2,topic:'定语从句',question:'I like the boy ______ is wearing a red T-shirt.',options:['A. who','B. which','C. what','D. whom'],answer:'A',explanation:'先行词the boy指人，在从句中作主语，用关系代词who。which指物，whom指人作宾语。',steps:['先行词指人→who/whom/that','从句缺主语→who（主格）','whom是宾格，不作主语'],source:'安徽中考真题'},

  // ═══════════════════════════════════════════
  // 语文 — 安徽中考语文（20题）
  // ═══════════════════════════════════════════
  { id:'ahzk_y001',year:2024,grade:'初中',subject:'chin',type:'选择题',difficulty:2,topic:'古诗文默写',question:'下列古诗文默写完全正确的一项是（ ）',options:['A. 大漠孤烟直，长河落日园','B. 海内存知已，天涯若比邻','C. 落红不是无情物，化作春泥更护花','D. 山重水复疑无路，柳岸花明又一村'],answer:'C',explanation:'A"园"应为"圆"；B"已"应为"己"；C正确（龚自珍《己亥杂诗》）；D"岸"应为"暗"。',steps:['A：长河落日"圆"','B：海内存"知己"','C：正确','D：柳"暗"花明又一村'],source:'安徽中考真题'},
  { id:'ahzk_y002',year:2024,grade:'初中',subject:'chin',type:'选择题',difficulty:2,topic:'字音',question:'下列词语中加点字注音完全正确的一项是（ ）',options:['A. 倔强(jué) 哺育(pǔ)','B. 称职(chèn) 模样(mú)','C. 惩罚(chěng) 氛围(fèn)','D. 追溯(shuò) 教诲(huǐ)'],answer:'B',explanation:'A"哺"应读bǔ；B全部正确（称职chènzhí，模样múyàng）；C"惩"应读chéng，"氛"应读fēn；D"溯"应读sù，"诲"应读huì。',steps:['A：哺bǔ','B：称chèn，模mú，全对','C：惩chéng，氛fēn','D：溯sù，诲huì'],source:'安徽中考真题'},
  { id:'ahzk_y003',year:2024,grade:'初中',subject:'chin',type:'选择题',difficulty:2,topic:'成语运用',question:'下列句子中加点成语使用恰当的一项是（ ）',options:['A. 他在课堂上夸夸其谈，同学们听得津津有味','B. 黄山风景巧夺天工，令人叹为观止','C. 同学们经常向老师请教，这种不耻下问的精神值得表扬','D. 这篇小说情节跌宕起伏，引人入胜'],answer:'D',explanation:'A"夸夸其谈"贬义，与语境不合；B"巧夺天工"用于人工胜过天然，黄山是自然景观，应用"鬼斧神工"；C"不耻下问"指地位高的人向地位低的人请教不觉得羞耻，学生向老师请教应用"虚心求教"；D正确。',steps:['A：夸夸其谈（贬义），语境不当','B：巧夺天工（人工），黄山是自然','C：不耻下问（下对上），学生→老师是上','D：引人入胜，正确'],source:'安徽中考真题'},
  { id:'ahzk_y004',year:2024,grade:'初中',subject:'chin',type:'选择题',difficulty:2,topic:'病句辨析',question:'下列句子没有语病的一项是（ ）',options:['A. 通过这次活动，使我开阔了眼界','B. 能否端正学习态度，是提高成绩的关键','C. 合肥的春天是一个美丽的城市','D. 为了防止类似事故再次发生，学校加强了安全教育'],answer:'D',explanation:'A缺少主语（删"通过"或"使"）；B两面对一面（删"能否"）；C主宾搭配不当（"春天"不是"城市"）；D正确。',steps:['A："通过...使..."缺主语','B："能否"两面与"是"一面不搭配','C："春天是城市"主宾不当','D：无病句'],source:'安徽中考真题'},
  { id:'ahzk_y005',year:2024,grade:'初中',subject:'chin',type:'选择题',difficulty:2,topic:'文言文词语',question:'下列句中加点词解释不正确的一项是（ ）',options:['A. 无案牍之劳形（形：形体、身体）','B. 濯清涟而不妖（濯：洗涤）','C. 便要还家（要：要求）','D. 属予作文以记之（属：同"嘱"，嘱托）'],answer:'C',explanation:'C中"要"是通假字，同"邀"，意为"邀请"。出自《桃花源记》"便要还家，设酒杀鸡作食"。',steps:['A：《陋室铭》，形=身体，正确','B：《爱莲说》，濯=洗涤，正确','C：《桃花源记》，要=邀，邀请，错误','D：《岳阳楼记》，属=嘱，正确'],source:'安徽中考真题'},

  // ═══════════════════════════════════════════
  // 生物 — 安徽中考生物（20题）
  // ═══════════════════════════════════════════
  { id:'ahzk_b001',year:2024,grade:'初中',subject:'bio',type:'选择题',difficulty:2,topic:'细胞结构',question:'与动物细胞相比，植物细胞特有的结构是（ ）',options:['A. 细胞膜','B. 细胞质','C. 细胞核','D. 细胞壁'],answer:'D',explanation:'植物细胞有细胞壁、叶绿体和液泡（成熟细胞有大液泡），动物细胞没有。细胞膜、细胞质、细胞核两者都有。',steps:['植物特有：细胞壁、叶绿体、大液泡','动物和植物共有：细胞膜、细胞质、细胞核'],source:'安徽中考真题'},
  { id:'ahzk_b002',year:2024,grade:'初中',subject:'bio',type:'选择题',difficulty:2,topic:'光合作用',question:'光合作用的原料是（ ）',options:['A. 有机物和氧气','B. 二氧化碳和水','C. 有机物和二氧化碳','D. 氧气和水'],answer:'B',explanation:'光合作用公式：CO₂ + H₂O →（光能/叶绿体）→ 有机物 + O₂。原料是CO₂和水。',steps:['光合作用：水+CO₂→有机物+O₂','原料：CO₂和水','产物：有机物和O₂'],source:'安徽中考真题'},
  { id:'ahzk_b003',year:2024,grade:'初中',subject:'bio',type:'选择题',difficulty:2,topic:'生态系统',question:'在生态系统中，下列属于生产者的是（ ）',options:['A. 细菌','B. 蘑菇','C. 草','D. 兔子'],answer:'C',explanation:'生产者是能进行光合作用制造有机物的生物（主要是绿色植物）。A大多为分解者，B为分解者，C为生产者，D为消费者。',steps:['生产者：绿色植物（光合作用）','消费者：动物','分解者：细菌、真菌'],source:'安徽中考真题'},
  { id:'ahzk_b004',year:2024,grade:'初中',subject:'bio',type:'选择题',difficulty:2,topic:'人体消化',question:'人体消化和吸收营养物质的主要器官是（ ）',options:['A. 口腔','B. 胃','C. 小肠','D. 大肠'],answer:'C',explanation:'小肠是消化和吸收的主要场所，具有长度长、绒毛多、消化液丰富等特点。',steps:['小肠长约5-6m，表面积大','有环形皱襞和绒毛','消化液丰富（肠液、胰液、胆汁）'],source:'安徽中考真题'},
  { id:'ahzk_b005',year:2024,grade:'初中',subject:'bio',type:'选择题',difficulty:2,topic:'遗传',question:'双眼皮（A）对单眼皮（a）为显性。一对双眼皮夫妇生了一个单眼皮孩子，则这对夫妇的基因型是（ ）',options:['A. AA和AA','B. AA和Aa','C. Aa和Aa','D. aa和aa'],answer:'C',explanation:'孩子单眼皮(aa)，分别从父母各获得一个a基因。父母都是双眼皮但没有aa，说明都是Aa。',steps:['孩子单眼皮aa→从父母各得一个a','父母双眼皮→不能是aa','父母基因型：Aa和Aa'],source:'安徽中考真题'}
];
