/* ========================================
   高二题库 — 高质量考题
   覆盖：数学 / 物理 / 化学 / 英语 / 生物
   ======================================== */

var gaoerQuestions = [

  // ═══════════════ 数学（导数·圆锥曲线·空间向量）═══════════════
  { id:'ge2m001',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'导数与极值',question:'函数 $f(x)=x^3-3x^2+1$ 的极大值点为（ ）',options:['A. $x=0$','B. $x=2$','C. $x=1$','D. $x=-1$'],answer:'A',explanation:'$f\'(x)=3x^2-6x=3x(x-2)$，驻点 $x=0,2$。$f\'\'(x)=6x-6$，$f\'\'(0)=-6<0$→极大值；$f\'\'(2)=6>0$→极小值。考点：导数求极值——一阶导找驻点，二阶导判类型。',steps:['$f\'(x)=3x^2-6x=3x(x-2)$，令$f\'(x)=0$得$x=0,2$','$f\'\'(x)=6x-6$','$f\'\'(0)=-6<0$→$x=0$为极大值点','$f\'\'(2)=6>0$→$x=2$为极小值点'],source:'高二数学·导数'},
  { id:'ge2m002',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'导数与切线',question:'曲线 $y=x^2+\\ln x$ 在 $x=1$ 处的切线斜率为（ ）',options:['A. 2','B. 3','C. 1','D. 4'],answer:'B',explanation:'$y\'=2x+\\frac{1}{x}$，$y\'(1)=2+1=3$。考点：导数几何意义——切线斜率等于导数值。',steps:['求导：$y\'=2x+\\frac{1}{x}$','代入$x=1$：$y\'(1)=2+1=3$'],source:'高二数学·导数'},
  { id:'ge2m003',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'圆锥曲线',question:'椭圆 $\\frac{x^2}{16}+\\frac{y^2}{9}=1$ 的焦点坐标为（ ）',options:['A. $(\\pm\\sqrt{7},0)$','B. $(0,\\pm\\sqrt{7})$','C. $(\\pm5,0)$','D. $(0,\\pm5)$'],answer:'A',explanation:'$a^2=16,b^2=9$，$c^2=a^2-b^2=7$，$c=\\sqrt{7}$。$a^2$在$x^2$下→长轴在x轴→焦点$(\\pm\\sqrt{7},0)$。考点：椭圆 $c^2=a^2-b^2$。',steps:['识别$a^2=16$，$b^2=9$','计算$c^2=a^2-b^2=7$','长轴在x轴→焦点$(\\pm\\sqrt{7},0)$'],source:'高二数学·圆锥曲线'},
  { id:'ge2m004',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:4,topic:'空间向量',question:'$\\vec{a}=(1,-2,2)$，$\\vec{b}=(2,1,-1)$，夹角余弦值为（ ）',options:['A. $-\\frac{\\sqrt{6}}{9}$','B. $\\frac{\\sqrt{6}}{9}$','C. $-\\frac{1}{3}$','D. $\\frac{1}{3}$'],answer:'A',explanation:'$\\vec{a}\\cdot\\vec{b}=2-2-2=-2$，$|\\vec{a}|=3$，$|\\vec{b}|=\\sqrt{6}$。$\\cos\\theta=\\frac{-2}{3\\sqrt{6}}=-\\frac{\\sqrt{6}}{9}$。考点：向量夹角余弦公式。',steps:['$\\vec{a}\\cdot\\vec{b}=1×2+(-2)×1+2×(-1)=-2$','$|\\vec{a}|=\\sqrt{1+4+4}=3$','$|\\vec{b}|=\\sqrt{4+1+1}=\\sqrt{6}$','$\\cos\\theta=\\frac{-2}{3\\sqrt{6}}=-\\frac{\\sqrt{6}}{9}$'],source:'高二数学·空间向量'},
  { id:'ge2m005',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'排列组合',question:'从5名男生和3名女生中选3人，至少1名女生，选法有（ ）',options:['A. 46种','B. 56种','C. 55种','D. 45种'],answer:'A',explanation:'总选法$C_8^3=56$，无女生$C_5^3=10$，至少1女生$=56-10=46$。考点：排列组合——正难则反。',steps:['$C_8^3=56$（总选法）','$C_5^3=10$（无女生）','$56-10=46$（至少1女生）'],source:'高二数学·排列组合'},
  { id:'ge2m006',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'二项式定理',question:'$(x-\\frac{1}{x})^6$ 展开式的常数项为（ ）',options:['A. -20','B. 20','C. -15','D. 15'],answer:'A',explanation:'$T_{k+1}=C_6^k x^{6-k}(-\\frac{1}{x})^k=C_6^k(-1)^k x^{6-2k}$。令$6-2k=0$得$k=3$，$T_4=C_6^3(-1)^3=20×(-1)=-20$。考点：二项式展开通项公式。',steps:['$T_{k+1}=C_6^k x^{6-k}(-x^{-1})^k=C_6^k(-1)^k x^{6-2k}$','令$6-2k=0$，$k=3$','$T_4=C_6^3(-1)^3=-20$'],source:'高二数学·二项式定理'},
  { id:'ge2m007',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'数列',question:'等差数列$\\{a_n\\}$，$a_1=2$，$a_3+a_5=10$，则$a_7=$（ ）',options:['A. 8','B. 10','C. 12','D. 14'],answer:'A',explanation:'$a_3=2+2d$，$a_5=2+4d$，$(2+2d)+(2+4d)=4+6d=10$，$d=1$。$a_7=2+6=8$。考点：等差数列通项。',steps:['$a_3=a_1+2d=2+2d$','$a_5=a_1+4d=2+4d$','$4+6d=10$，$d=1$','$a_7=a_1+6d=2+6=8$'],source:'高二数学·数列'},

  // ═══════════════ 物理（电磁学·热力学·光学）═══════════════
  { id:'ge2p001',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'电场强度',question:'真空中点电荷$Q$产生的电场中，距离$r$处场强为$E$。$Q$加倍、$r$加倍，场强变为原来的（ ）',options:['A. 0.5倍','B. 1倍','C. 2倍','D. 4倍'],answer:'A',explanation:'$E=k\\frac{Q}{r^2}$，$E\'=k\\frac{2Q}{(2r)^2}=k\\frac{2Q}{4r^2}=\\frac{1}{2}E$。考点：点电荷场强公式。',steps:['$E=k\\frac{Q}{r^2}$','$E\'=k\\frac{2Q}{4r^2}=\\frac{1}{2}E$'],source:'高二物理·电场'},
  { id:'ge2p002',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'恒定电流',question:'均匀导线拉长至原长2倍（体积不变），电阻变为原来的（ ）',options:['A. 2倍','B. 4倍','C. 8倍','D. 16倍'],answer:'B',explanation:'$R=\\rho\\frac{L}{S}$。$L\'=2L$，体积不变→$S\'=S/2$。$R\'=\\rho\\frac{2L}{S/2}=4\\rho\\frac{L}{S}=4R$。考点：电阻定律。',steps:['$R=\\rho\\frac{L}{S}$','长度×2 → 截面积÷2（体积不变）','$R\'=\\rho\\frac{2L}{S/2}=4R$'],source:'高二物理·恒定电流'},
  { id:'ge2p003',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'闭合电路欧姆定律',question:'电源$E$、内阻$r$，外电阻$R$增大时，正确的是（ ）',options:['A. 路端电压增大','B. 电流增大','C. 内电压增大','D. 输出功率一定增大'],answer:'A',explanation:'$I=\\frac{E}{R+r}$，$R$↑→$I$↓。路端电压$U=E-Ir$，$I$↓→$U$↑。内电压$Ir$↓。输出功率$P=I^2R$非单调（$R=r$时最大）。考点：闭合电路欧姆定律。',steps:['$I=E/(R+r)$，$R$增大→$I$减小','$U=E-Ir$，$I$减小→$U$增大','内电压$Ir$随$I$减小','输出功率变化非单调'],source:'高二物理·电路'},
  { id:'ge2p004',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:4,topic:'电磁感应',question:'闭合线圈在匀强磁场中转动，转速加倍，感应电动势最大值变为原来的（ ）',options:['A. 0.5倍','B. 1倍','C. 2倍','D. 4倍'],answer:'C',explanation:'$E_m=NBS\\omega$，$\\omega=2\\pi n$。转速$n$加倍→$\\omega$加倍→$E_m$加倍。考点：交流电——感应电动势最大值。',steps:['$E_m=NBS\\omega$','$\\omega=2\\pi n$','$n\'/=2n$→$\\omega\'=2\\omega$→$E_m\'=2E_m$'],source:'高二物理·电磁感应'},
  { id:'ge2p005',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'变压器',question:'理想变压器原线圈100匝，副线圈200匝，原线圈接220V交流，副线圈电压为（ ）',options:['A. 110V','B. 220V','C. 440V','D. 880V'],answer:'C',explanation:'$\\frac{U_1}{U_2}=\\frac{n_1}{n_2}$，$U_2=\\frac{n_2}{n_1}U_1=\\frac{200}{100}×220=440$V。考点：理想变压器电压关系。',steps:['$\\frac{U_1}{U_2}=\\frac{n_1}{n_2}$','$U_2=\\frac{200}{100}×220=440$V'],source:'高二物理·变压器'},
  { id:'ge2p006',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:4,topic:'热力学',question:'理想气体等温膨胀，体积加倍，压强变为原来的（ ）',options:['A. 2倍','B. 1倍','C. 0.5倍','D. 4倍'],answer:'C',explanation:'玻意耳定律：$p_1V_1=p_2V_2$（等温）。$V_2=2V_1$→$p_2=p_1/2$。考点：等温过程——玻意耳定律。',steps:['$p_1V_1=p_2V_2$','$V_2=2V_1$','$p_2=p_1V_1/(2V_1)=p_1/2$'],source:'高二物理·热力学'},
  { id:'ge2p007',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'分子动理论',question:'一定质量理想气体，温度不变时，体积增大，气体压强变化的原因是（ ）',options:['A. 分子平均动能增大','B. 单位面积碰撞次数减少','C. 分子平均动能减小','D. 分子数减少'],answer:'B',explanation:'温度不变→分子平均动能不变。体积增大→分子数密度减小→单位时间单位面积碰撞次数减少→压强减小。考点：气体压强的微观解释。',steps:['温度不变→分子平均动能不变','体积增大→分子密度减小','单位面积碰撞次数减少→压强减小'],source:'高二物理·热学'},

  // ═══════════════ 化学（有机·平衡·电化学）═══════════════
  { id:'ge2c001',year:2024,grade:'高二',subject:'chem',type:'选择题',difficulty:3,topic:'有机化学',question:'下列有机物中，属于烷烃的是（ ）',options:['A. $C_2H_4$','B. $C_2H_2$','C. $C_2H_6$','D. $C_6H_6$'],answer:'C',explanation:'烷烃通式 $C_nH_{2n+2}$。$C_2H_6$（乙烷）符合$n=2$时$C_2H_6$。$C_2H_4$为烯烃，$C_2H_2$为炔烃，$C_6H_6$为苯。考点：烷烃通式。',steps:['烷烃通式：$C_nH_{2n+2}$','$C_2H_6$：$2n+2=6$，$n=2$，符合','$C_2H_4$：$H$不足（烯烃）；$C_2H_2$：$H$更少（炔烃）'],source:'高二化学·有机化学'},
  { id:'ge2c002',year:2024,grade:'高二',subject:'chem',type:'选择题',difficulty:3,topic:'化学平衡',question:'反应 $2NO_2(g)\\rightleftharpoons N_2O_4(g)$，$\\Delta H<0$。使$NO_2$转化率增大的措施是（ ）',options:['A. 升温','B. 减压','C. 加压','D. 加催化剂'],answer:'C',explanation:'$\\Delta H<0$→放热反应。$\\Delta n<0$（2→1），加压平衡向气体分子数减少方向（正向）移动，$NO_2$转化率增大。升温向吸热方向（逆向）移动。催化剂不改变平衡。考点：勒夏特列原理。',steps:['$\\Delta n=1-2=-1<0$→正向气体分子数减少','加压→平衡正向移动→转化率增大','升温→平衡逆向移动','催化剂不影响平衡'],source:'高二化学·化学平衡'},
  { id:'ge2c003',year:2024,grade:'高二',subject:'chem',type:'选择题',difficulty:4,topic:'电化学',question:'用惰性电极电解$CuSO_4$溶液，阳极发生的反应是（ ）',options:['A. $Cu^{2+}+2e^-=Cu$','B. $2H^++2e^-=H_2\\uparrow$','C. $4OH^--4e^-=2H_2O+O_2\\uparrow$','D. $Cu-2e^-=Cu^{2+}$'],answer:'C',explanation:'惰性电极电解$CuSO_4$，阳极是$OH^-$放电（比$SO_4^{2-}$更易失电子）：$4OH^--4e^-=2H_2O+O_2\\uparrow$。阴极$Cu^{2+}$放电：$Cu^{2+}+2e^-=Cu$。考点：电解池——阳极氧化反应。',steps:['阳极：阴离子放电，$OH^-$优先于$SO_4^{2-}$','$4OH^--4e^-=2H_2O+O_2\\uparrow$','A是阴极反应，D是活性阳极'],source:'高二化学·电化学'},
  { id:'ge2c004',year:2024,grade:'高二',subject:'chem',type:'选择题',difficulty:3,topic:'电离平衡',question:'$25°C$时，$pH=3$的盐酸中，$[H^+]$为（ ）mol/L',options:['A. $10^{-3}$','B. $10^{-11}$','C. $3$','D. $10^{-7}$'],answer:'A',explanation:'$pH=-\\lg[H^+]$，$[H^+]=10^{-pH}=10^{-3}$mol/L。考点：pH的定义。',steps:['$pH=-\\lg[H^+]$','$[H^+]=10^{-pH}=10^{-3}$mol/L'],source:'高二化学·电离平衡'},

  // 更多数学题
  { id:'ge2m008',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:4,topic:'圆锥曲线',question:'双曲线 $\\frac{x^2}{9}-\\frac{y^2}{16}=1$ 的离心率为（ ）',options:['A. $\\frac{5}{3}$','B. $\\frac{4}{3}$','C. $\\frac{3}{4}$','D. $\\frac{5}{4}$'],answer:'A',explanation:'$a^2=9,b^2=16$，$c^2=a^2+b^2=25$，$c=5$。$e=\\frac{c}{a}=\\frac{5}{3}$。考点：双曲线离心率$e=\\frac{c}{a}>1$。易错：双曲线$c^2=a^2+b^2$（与椭圆$c^2=a^2-b^2$不同）。',steps:['$a^2=9$→$a=3$','$b^2=16$','双曲线$c^2=a^2+b^2=25$→$c=5$','$e=c/a=5/3$'],source:'高二数学·双曲线'},
  { id:'ge2m009',year:2024,grade:'高二',subject:'math',type:'选择题',difficulty:3,topic:'复数',question:'复数 $z=\\frac{2-i}{1+i}$ 的实部为（ ）',options:['A. $\\frac{1}{2}$','B. $\\frac{3}{2}$','C. 1','D. 0'],answer:'A',explanation:'分子分母同乘$1-i$：$z=\\frac{(2-i)(1-i)}{(1+i)(1-i)}=\\frac{2-2i-i+i^2}{1+1}=\\frac{1-3i}{2}=\\frac{1}{2}-\\frac{3}{2}i$，实部$\\frac{1}{2}$。考点：复数除法——分母实数化。',steps:['同乘分母共轭$(1-i)$','分子展开：$(2-i)(1-i)=2-2i-i+i^2=1-3i$','分母：$1+1=2$','$z=\\frac{1}{2}-\\frac{3}{2}i$，实部$\\frac{1}{2}$'],source:'高二数学·复数'},

  // 更多物理题
  { id:'ge2p008',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:4,topic:'带电粒子在磁场中的运动',question:'带电粒子垂直进入匀强磁场做匀速圆周运动，速度加倍，周期（ ）',options:['A. 变为2倍','B. 变为1/2','C. 变为4倍','D. 不变'],answer:'D',explanation:'$T=\\frac{2\\pi m}{qB}$，周期与速度无关（仅由$m,q,B$决定）。速度加倍→半径加倍，但周期不变。考点：带电粒子在磁场中的运动周期公式。',steps:['$T=\\frac{2\\pi m}{qB}$','公式中不含速度$v$','周期与速度无关'],source:'高二物理·磁场'},
  { id:'ge2p009',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'安培力',question:'导线长$L=1$m，电流$I=2$A，与磁场$B=0.5$T垂直放置，安培力大小为（ ）',options:['A. 0.5N','B. 1N','C. 2N','D. 4N'],answer:'B',explanation:'$F=BIL\\sin\\theta=0.5×2×1×\\sin90°=1$N。考点：安培力公式。',steps:['$F=BIL\\sin\\theta$','$\\theta=90°$→$\\sin90°=1$','$F=0.5×2×1=1$N'],source:'高二物理·安培力'},
  { id:'ge2p010',year:2024,grade:'高二',subject:'phys',type:'选择题',difficulty:3,topic:'光电效应',question:'金属逸出功$W_0$，频率$\\nu$的光恰好发生光电效应。频率变$2\\nu$时，最大初动能为（ ）',options:['A. 0','B. $h\\nu$','C. $2h\\nu$','D. $h\\nu-W_0$'],answer:'B',explanation:'恰好发生→$h\\nu=W_0$。$2\\nu$时：$E_{km}=h(2\\nu)-W_0=2h\\nu-h\\nu=h\\nu$。考点：爱因斯坦光电效应方程 $E_{km}=h\\nu-W_0$。',steps:['恰好发生：$h\\nu=W_0$','$E_{km}=h(2\\nu)-W_0=2h\\nu-h\\nu$','$=h\\nu$'],source:'高二物理·光电效应'},

  // 更多化学题
  { id:'ge2c005',year:2024,grade:'高二',subject:'chem',type:'选择题',difficulty:3,topic:'盐类水解',question:'下列盐的水溶液呈碱性的是（ ）',options:['A. NaCl','B. $NH_4Cl$','C. $Na_2CO_3$','D. $KNO_3$'],answer:'C',explanation:'$Na_2CO_3$是强碱弱酸盐，$CO_3^{2-}$水解：$CO_3^{2-}+H_2O\\rightleftharpoons HCO_3^-+OH^-$，溶液呈碱性。NaCl和$KNO_3$为强酸强碱盐，中性。$NH_4Cl$为强酸弱碱盐，$NH_4^+$水解呈酸性。考点：盐类水解——谁强显谁性。',steps:['$Na_2CO_3$：强碱(NaOH)+弱酸($H_2CO_3$)→碱性','NaCl、$KNO_3$：强酸+强碱→中性','$NH_4Cl$：强酸(HCl)+弱碱($NH_3·H_2O$)→酸性'],source:'高二化学·盐类水解'}
];

console.log('gaoerQuestions loaded: ' + gaoerQuestions.length + ' questions');
